"""
    CryptoAPIs

    Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.new_block_e400 import NewBlockE400
globals()['NewBlockE400'] = NewBlockE400
from cryptoapis.model.inline_response40065 import InlineResponse40065


class TestInlineResponse40065(unittest.TestCase):
    """InlineResponse40065 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse40065(self):
        """Test InlineResponse40065"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse40065()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
