"""
    CryptoAPIs

    Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.get_eip1559_fee_recommendations_ri import GetEIP1559FeeRecommendationsRI
globals()['GetEIP1559FeeRecommendationsRI'] = GetEIP1559FeeRecommendationsRI
from cryptoapis.model.get_eip1559_fee_recommendations_r_data import GetEIP1559FeeRecommendationsRData


class TestGetEIP1559FeeRecommendationsRData(unittest.TestCase):
    """GetEIP1559FeeRecommendationsRData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEIP1559FeeRecommendationsRData(self):
        """Test GetEIP1559FeeRecommendationsRData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEIP1559FeeRecommendationsRData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
