"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.sync_new_hd_wallet_x_pub_y_pub_z_pub_e400 import SyncNewHDWalletXPubYPubZPubE400
globals()['SyncNewHDWalletXPubYPubZPubE400'] = SyncNewHDWalletXPubYPubZPubE400
from cryptoapis.model.sync_new_hd_wallet_x_pub_y_pub_z_pub400_response import SyncNewHDWalletXPubYPubZPub400Response


class TestSyncNewHDWalletXPubYPubZPub400Response(unittest.TestCase):
    """SyncNewHDWalletXPubYPubZPub400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSyncNewHDWalletXPubYPubZPub400Response(self):
        """Test SyncNewHDWalletXPubYPubZPub400Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SyncNewHDWalletXPubYPubZPub400Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
