# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cryptoapis
from cryptoapis.models.list_confirmed_transactions_by_address_ribsd2_vin_inner_script_sig import ListConfirmedTransactionsByAddressRIBSD2VinInnerScriptSig  # noqa: E501
from cryptoapis.rest import ApiException

class TestListConfirmedTransactionsByAddressRIBSD2VinInnerScriptSig(unittest.TestCase):
    """ListConfirmedTransactionsByAddressRIBSD2VinInnerScriptSig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListConfirmedTransactionsByAddressRIBSD2VinInnerScriptSig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListConfirmedTransactionsByAddressRIBSD2VinInnerScriptSig`
        """
        model = cryptoapis.models.list_confirmed_transactions_by_address_ribsd2_vin_inner_script_sig.ListConfirmedTransactionsByAddressRIBSD2VinInnerScriptSig()  # noqa: E501
        if include_optional :
            return ListConfirmedTransactionsByAddressRIBSD2VinInnerScriptSig(
                asm = 'OP_DUP OP_HASH160 1ec5c66e9789c655ae068d35088b4073345fe0b0 OP_EQUALVERIFY OP_CHECKSIG', 
                hex = '76a9141ec5c66e9789c655ae068d35088b4073345fe0b088ac', 
                type = 'scripthash'
            )
        else :
            return ListConfirmedTransactionsByAddressRIBSD2VinInnerScriptSig(
                asm = 'OP_DUP OP_HASH160 1ec5c66e9789c655ae068d35088b4073345fe0b0 OP_EQUALVERIFY OP_CHECKSIG',
                hex = '76a9141ec5c66e9789c655ae068d35088b4073345fe0b088ac',
                type = 'scripthash',
        )
        """

    def testListConfirmedTransactionsByAddressRIBSD2VinInnerScriptSig(self):
        """Test ListConfirmedTransactionsByAddressRIBSD2VinInnerScriptSig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
