"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.get_hd_wallet_x_pub_y_pub_z_pub_details_e400 import GetHDWalletXPubYPubZPubDetailsE400
globals()['GetHDWalletXPubYPubZPubDetailsE400'] = GetHDWalletXPubYPubZPubDetailsE400
from cryptoapis.model.get_hd_wallet_x_pub_y_pub_z_pub_details400_response import GetHDWalletXPubYPubZPubDetails400Response


class TestGetHDWalletXPubYPubZPubDetails400Response(unittest.TestCase):
    """GetHDWalletXPubYPubZPubDetails400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetHDWalletXPubYPubZPubDetails400Response(self):
        """Test GetHDWalletXPubYPubZPubDetails400Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetHDWalletXPubYPubZPubDetails400Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
