# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cryptoapis
from cryptoapis.models.get_transaction_details_by_transaction_idribsd2 import GetTransactionDetailsByTransactionIDRIBSD2  # noqa: E501
from cryptoapis.rest import ApiException

class TestGetTransactionDetailsByTransactionIDRIBSD2(unittest.TestCase):
    """GetTransactionDetailsByTransactionIDRIBSD2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetTransactionDetailsByTransactionIDRIBSD2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTransactionDetailsByTransactionIDRIBSD2`
        """
        model = cryptoapis.models.get_transaction_details_by_transaction_idribsd2.GetTransactionDetailsByTransactionIDRIBSD2()  # noqa: E501
        if include_optional :
            return GetTransactionDetailsByTransactionIDRIBSD2(
                locktime = 0, 
                size = 125, 
                version = 1, 
                vin = [
                    cryptoapis.models.get_transaction_details_by_transaction_idribsd2_vin_inner.GetTransactionDetailsByTransactionIDRIBSD2_vin_inner(
                        addresses = [
                            '7W7gfYstwDR6a2ZCxEidAuvshyomqJ8yXT'
                            ], 
                        coinbase = '03dcf4150c0b2f454233322f414431322f04da88506004565cc01f0c3130fc5f4e050000000000000a626368706f6f6c172f20626974636f696e636173682e6e6574776f726b202f', 
                        script_sig = cryptoapis.models.get_transaction_details_by_transaction_idribsd2_vin_inner_script_sig.GetTransactionDetailsByTransactionIDRIBSD2_vin_inner_scriptSig(
                            asm = 'OP_DUP OP_HASH160 1fd680935cd42f95702493d44c8de964a42656b5 OP_EQUALVERIFY OP_CHECKSIG', 
                            hex = '4197968cb34bfba488b4a2399f7959b823fefad79ca0b5ed3f3a4bec4c0286cab55b896b28bbbcd4e61cf584cecfd47063b18b481d8d680eafbf869ada1a02c52441210237a84e6d70e775f274e4cbd9f30f9f8b1a426e8b08a9f802a851ce501c930011', 
                            type = 'scripthash', ), 
                        sequence = 4294967295, 
                        txid = 'f60cf447159b08e9857cbc96688ba80beff23c6f032f6545044ab40a771b15f5', 
                        txinwitness = [
                            '3045022100c11ea5740bcd69f0f68a4914279838014d28923134d18e05c5a5486dfd06cc8c02200dadccec3f07bed0d1040f9e5a155efa5fdd40fc91f92342578d26848da4c6b901'
                            ], 
                        value = '0.2354', 
                        vout = 1, )
                    ], 
                vout = [
                    cryptoapis.models.get_transaction_details_by_transaction_idribsd2_vout_inner.GetTransactionDetailsByTransactionIDRIBSD2_vout_inner(
                        is_spent = False, 
                        script_pub_key = cryptoapis.models.get_transaction_details_by_transaction_idribsd2_vout_inner_script_pub_key.GetTransactionDetailsByTransactionIDRIBSD2_vout_inner_scriptPubKey(
                            addresses = [
                                ''
                                ], 
                            asm = 'OP_DUP OP_HASH160 4112d3f2cc01db043c0e638bb6338c83a7b9aa8f OP_EQUALVERIFY OP_CHECKSIG', 
                            hex = '76a9144112d3f2cc01db043c0e638bb6338c83a7b9aa8f88ac', 
                            req_sigs = 1, 
                            type = 'scripthash', ), 
                        value = '0.5896', )
                    ]
            )
        else :
            return GetTransactionDetailsByTransactionIDRIBSD2(
                locktime = 0,
                size = 125,
                version = 1,
                vin = [
                    cryptoapis.models.get_transaction_details_by_transaction_idribsd2_vin_inner.GetTransactionDetailsByTransactionIDRIBSD2_vin_inner(
                        addresses = [
                            '7W7gfYstwDR6a2ZCxEidAuvshyomqJ8yXT'
                            ], 
                        coinbase = '03dcf4150c0b2f454233322f414431322f04da88506004565cc01f0c3130fc5f4e050000000000000a626368706f6f6c172f20626974636f696e636173682e6e6574776f726b202f', 
                        script_sig = cryptoapis.models.get_transaction_details_by_transaction_idribsd2_vin_inner_script_sig.GetTransactionDetailsByTransactionIDRIBSD2_vin_inner_scriptSig(
                            asm = 'OP_DUP OP_HASH160 1fd680935cd42f95702493d44c8de964a42656b5 OP_EQUALVERIFY OP_CHECKSIG', 
                            hex = '4197968cb34bfba488b4a2399f7959b823fefad79ca0b5ed3f3a4bec4c0286cab55b896b28bbbcd4e61cf584cecfd47063b18b481d8d680eafbf869ada1a02c52441210237a84e6d70e775f274e4cbd9f30f9f8b1a426e8b08a9f802a851ce501c930011', 
                            type = 'scripthash', ), 
                        sequence = 4294967295, 
                        txid = 'f60cf447159b08e9857cbc96688ba80beff23c6f032f6545044ab40a771b15f5', 
                        txinwitness = [
                            '3045022100c11ea5740bcd69f0f68a4914279838014d28923134d18e05c5a5486dfd06cc8c02200dadccec3f07bed0d1040f9e5a155efa5fdd40fc91f92342578d26848da4c6b901'
                            ], 
                        value = '0.2354', 
                        vout = 1, )
                    ],
                vout = [
                    cryptoapis.models.get_transaction_details_by_transaction_idribsd2_vout_inner.GetTransactionDetailsByTransactionIDRIBSD2_vout_inner(
                        is_spent = False, 
                        script_pub_key = cryptoapis.models.get_transaction_details_by_transaction_idribsd2_vout_inner_script_pub_key.GetTransactionDetailsByTransactionIDRIBSD2_vout_inner_scriptPubKey(
                            addresses = [
                                ''
                                ], 
                            asm = 'OP_DUP OP_HASH160 4112d3f2cc01db043c0e638bb6338c83a7b9aa8f OP_EQUALVERIFY OP_CHECKSIG', 
                            hex = '76a9144112d3f2cc01db043c0e638bb6338c83a7b9aa8f88ac', 
                            req_sigs = 1, 
                            type = 'scripthash', ), 
                        value = '0.5896', )
                    ],
        )
        """

    def testGetTransactionDetailsByTransactionIDRIBSD2(self):
        """Test GetTransactionDetailsByTransactionIDRIBSD2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
