# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cryptoapis
from cryptoapis.models.create_automatic_coins_forwarding_r_data import CreateAutomaticCoinsForwardingRData  # noqa: E501
from cryptoapis.rest import ApiException

class TestCreateAutomaticCoinsForwardingRData(unittest.TestCase):
    """CreateAutomaticCoinsForwardingRData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateAutomaticCoinsForwardingRData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAutomaticCoinsForwardingRData`
        """
        model = cryptoapis.models.create_automatic_coins_forwarding_r_data.CreateAutomaticCoinsForwardingRData()  # noqa: E501
        if include_optional :
            return CreateAutomaticCoinsForwardingRData(
                item = cryptoapis.models.create_automatic_coins_forwarding_ri.CreateAutomaticCoinsForwardingRI(
                    callback_url = 'https://example.com', 
                    confirmations_count = 3, 
                    created_timestamp = 1611238648, 
                    fee_priority = 'standard', 
                    from_address = 'mzAsK3csTnozLnYVdca4gaoH1btBZBC6QB', 
                    minimum_transfer_amount = '0.0002', 
                    reference_id = '6017c964973cdcf4d4f69e29', 
                    to_address = 'mzYijhgmzZrmuB7wBDazRKirnChKyow4M3', )
            )
        else :
            return CreateAutomaticCoinsForwardingRData(
                item = cryptoapis.models.create_automatic_coins_forwarding_ri.CreateAutomaticCoinsForwardingRI(
                    callback_url = 'https://example.com', 
                    confirmations_count = 3, 
                    created_timestamp = 1611238648, 
                    fee_priority = 'standard', 
                    from_address = 'mzAsK3csTnozLnYVdca4gaoH1btBZBC6QB', 
                    minimum_transfer_amount = '0.0002', 
                    reference_id = '6017c964973cdcf4d4f69e29', 
                    to_address = 'mzYijhgmzZrmuB7wBDazRKirnChKyow4M3', ),
        )
        """

    def testCreateAutomaticCoinsForwardingRData(self):
        """Test CreateAutomaticCoinsForwardingRData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
