"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.get_asset_details_by_asset_idri_asset_logo import GetAssetDetailsByAssetIDRIAssetLogo
from cryptoapis.model.get_asset_details_by_asset_idri_latest_rate import GetAssetDetailsByAssetIDRILatestRate
from cryptoapis.model.get_asset_details_by_asset_symbol_ris import GetAssetDetailsByAssetSymbolRIS
globals()['GetAssetDetailsByAssetIDRIAssetLogo'] = GetAssetDetailsByAssetIDRIAssetLogo
globals()['GetAssetDetailsByAssetIDRILatestRate'] = GetAssetDetailsByAssetIDRILatestRate
globals()['GetAssetDetailsByAssetSymbolRIS'] = GetAssetDetailsByAssetSymbolRIS
from cryptoapis.model.get_asset_details_by_asset_symbol_ri import GetAssetDetailsByAssetSymbolRI


class TestGetAssetDetailsByAssetSymbolRI(unittest.TestCase):
    """GetAssetDetailsByAssetSymbolRI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAssetDetailsByAssetSymbolRI(self):
        """Test GetAssetDetailsByAssetSymbolRI"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAssetDetailsByAssetSymbolRI()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
