# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cryptoapis
from cryptoapis.models.list_zilliqa_transactions_by_block_hash_ri import ListZilliqaTransactionsByBlockHashRI  # noqa: E501
from cryptoapis.rest import ApiException

class TestListZilliqaTransactionsByBlockHashRI(unittest.TestCase):
    """ListZilliqaTransactionsByBlockHashRI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListZilliqaTransactionsByBlockHashRI
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListZilliqaTransactionsByBlockHashRI`
        """
        model = cryptoapis.models.list_zilliqa_transactions_by_block_hash_ri.ListZilliqaTransactionsByBlockHashRI()  # noqa: E501
        if include_optional :
            return ListZilliqaTransactionsByBlockHashRI(
                fee = cryptoapis.models.get_zilliqa_transaction_details_by_transaction_idri_fee.GetZilliqaTransactionDetailsByTransactionIDRI_fee(
                    amount = '0.000235', 
                    unit = 'ZIL', ), 
                gas_limit = 550000, 
                gas_price = 2994782927, 
                gas_used = 24673, 
                mined_in_block_height = 1250392, 
                nonce = 13, 
                recipients = [
                    cryptoapis.models.list_zilliqa_transactions_by_address_ri_recipients_inner.ListZilliqaTransactionsByAddressRI_recipients_inner(
                        address = 'zil1v25at4s3eh9w34uqqhe3vdvfsvcwq6un3fupc2', 
                        amount = '0', )
                    ], 
                senders = [
                    cryptoapis.models.list_zilliqa_transactions_by_address_ri_senders_inner.ListZilliqaTransactionsByAddressRI_senders_inner(
                        address = 'zil1uhn7627k6xl5f03sq6grje5lk3gy0kf5aptz83', 
                        amount = '0', )
                    ], 
                timestamp = 1582202940, 
                transaction_hash = '0xf4a847a1489a043ee509d5d7df48f2bf7ba1b15354ed14600b035ff2f7670203', 
                transaction_index = 0, 
                transaction_status = '0'
            )
        else :
            return ListZilliqaTransactionsByBlockHashRI(
                fee = cryptoapis.models.get_zilliqa_transaction_details_by_transaction_idri_fee.GetZilliqaTransactionDetailsByTransactionIDRI_fee(
                    amount = '0.000235', 
                    unit = 'ZIL', ),
                gas_limit = 550000,
                gas_price = 2994782927,
                gas_used = 24673,
                mined_in_block_height = 1250392,
                nonce = 13,
                recipients = [
                    cryptoapis.models.list_zilliqa_transactions_by_address_ri_recipients_inner.ListZilliqaTransactionsByAddressRI_recipients_inner(
                        address = 'zil1v25at4s3eh9w34uqqhe3vdvfsvcwq6un3fupc2', 
                        amount = '0', )
                    ],
                senders = [
                    cryptoapis.models.list_zilliqa_transactions_by_address_ri_senders_inner.ListZilliqaTransactionsByAddressRI_senders_inner(
                        address = 'zil1uhn7627k6xl5f03sq6grje5lk3gy0kf5aptz83', 
                        amount = '0', )
                    ],
                timestamp = 1582202940,
                transaction_hash = '0xf4a847a1489a043ee509d5d7df48f2bf7ba1b15354ed14600b035ff2f7670203',
                transaction_index = 0,
                transaction_status = '0',
        )
        """

    def testListZilliqaTransactionsByBlockHashRI(self):
        """Test ListZilliqaTransactionsByBlockHashRI"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
