# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cryptoapis
from cryptoapis.models.prepare_a_non_fungible_token_transfer_from_address_ribse import PrepareANonFungibleTokenTransferFromAddressRIBSE  # noqa: E501
from cryptoapis.rest import ApiException

class TestPrepareANonFungibleTokenTransferFromAddressRIBSE(unittest.TestCase):
    """PrepareANonFungibleTokenTransferFromAddressRIBSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PrepareANonFungibleTokenTransferFromAddressRIBSE
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrepareANonFungibleTokenTransferFromAddressRIBSE`
        """
        model = cryptoapis.models.prepare_a_non_fungible_token_transfer_from_address_ribse.PrepareANonFungibleTokenTransferFromAddressRIBSE()  # noqa: E501
        if include_optional :
            return PrepareANonFungibleTokenTransferFromAddressRIBSE(
                data_hex = '0x23b872dd000000000000000000000000c6d46aba0c6e2eb6358c4e24804158cc4d8479220000000000000000000000000902a667d6a3f287835e0a4593cae4167384abc6000000000000000000000000000000000000000000000000000000000000000e', 
                nonce = '1', 
                sig_hash = '1b0ba4f497e39a74aa9a83afde0ec257c5c6e8547ea8187c319f0a242c2506f4', 
                fee = cryptoapis.models.prepare_a_non_fungible_token_transfer_from_address_ribse_fee.PrepareANonFungibleTokenTransferFromAddressRIBSE_fee(
                    gas_limit = '552020', 
                    gas_price = '2500000007', 
                    max_fee_per_gas = '6655534951', 
                    max_priority_fee_per_gas = '1000000000', ), 
                transaction_type = 'access-list-transaction'
            )
        else :
            return PrepareANonFungibleTokenTransferFromAddressRIBSE(
                sig_hash = '1b0ba4f497e39a74aa9a83afde0ec257c5c6e8547ea8187c319f0a242c2506f4',
                fee = cryptoapis.models.prepare_a_non_fungible_token_transfer_from_address_ribse_fee.PrepareANonFungibleTokenTransferFromAddressRIBSE_fee(
                    gas_limit = '552020', 
                    gas_price = '2500000007', 
                    max_fee_per_gas = '6655534951', 
                    max_priority_fee_per_gas = '1000000000', ),
                transaction_type = 'access-list-transaction',
        )
        """

    def testPrepareANonFungibleTokenTransferFromAddressRIBSE(self):
        """Test PrepareANonFungibleTokenTransferFromAddressRIBSE"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
