# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cryptoapis
from cryptoapis.models.get_transaction_details_by_transaction_id_from_callback_ribsx import GetTransactionDetailsByTransactionIDFromCallbackRIBSX  # noqa: E501
from cryptoapis.rest import ApiException

class TestGetTransactionDetailsByTransactionIDFromCallbackRIBSX(unittest.TestCase):
    """GetTransactionDetailsByTransactionIDFromCallbackRIBSX unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetTransactionDetailsByTransactionIDFromCallbackRIBSX
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTransactionDetailsByTransactionIDFromCallbackRIBSX`
        """
        model = cryptoapis.models.get_transaction_details_by_transaction_id_from_callback_ribsx.GetTransactionDetailsByTransactionIDFromCallbackRIBSX()  # noqa: E501
        if include_optional :
            return GetTransactionDetailsByTransactionIDFromCallbackRIBSX(
                additional_data = 'rPmPErQe4g9725pcNxJpuvKkdqTESTQ6Tu', 
                destination_tag = 3999472835, 
                offer = cryptoapis.models.get_xrp_ripple_transaction_details_by_transaction_idri_offer.GetXRPRippleTransactionDetailsByTransactionIDRI_offer(
                    amount = '3.0154', 
                    unit = 'XRP', ), 
                receive = cryptoapis.models.get_xrp_ripple_transaction_details_by_transaction_idri_receive.GetXRPRippleTransactionDetailsByTransactionIDRI_receive(
                    amount = '2.1256', 
                    unit = 'XRP', ), 
                sequence = 4294967295, 
                status = 'tesSUCCESS', 
                type = 'Payment', 
                value = cryptoapis.models.get_transaction_details_by_transaction_id_from_callback_ribsx_value.GetTransactionDetailsByTransactionIDFromCallbackRIBSX_value(
                    amount = '0.000001', 
                    unit = 'XRP', )
            )
        else :
            return GetTransactionDetailsByTransactionIDFromCallbackRIBSX(
                additional_data = 'rPmPErQe4g9725pcNxJpuvKkdqTESTQ6Tu',
                offer = cryptoapis.models.get_xrp_ripple_transaction_details_by_transaction_idri_offer.GetXRPRippleTransactionDetailsByTransactionIDRI_offer(
                    amount = '3.0154', 
                    unit = 'XRP', ),
                receive = cryptoapis.models.get_xrp_ripple_transaction_details_by_transaction_idri_receive.GetXRPRippleTransactionDetailsByTransactionIDRI_receive(
                    amount = '2.1256', 
                    unit = 'XRP', ),
                sequence = 4294967295,
                status = 'tesSUCCESS',
                type = 'Payment',
                value = cryptoapis.models.get_transaction_details_by_transaction_id_from_callback_ribsx_value.GetTransactionDetailsByTransactionIDFromCallbackRIBSX_value(
                    amount = '0.000001', 
                    unit = 'XRP', ),
        )
        """

    def testGetTransactionDetailsByTransactionIDFromCallbackRIBSX(self):
        """Test GetTransactionDetailsByTransactionIDFromCallbackRIBSX"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
