"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.get_latest_mined_xrp_ripple_block_e401 import GetLatestMinedXRPRippleBlockE401
globals()['GetLatestMinedXRPRippleBlockE401'] = GetLatestMinedXRPRippleBlockE401
from cryptoapis.model.get_latest_mined_xrp_ripple_block401_response import GetLatestMinedXRPRippleBlock401Response


class TestGetLatestMinedXRPRippleBlock401Response(unittest.TestCase):
    """GetLatestMinedXRPRippleBlock401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetLatestMinedXRPRippleBlock401Response(self):
        """Test GetLatestMinedXRPRippleBlock401Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetLatestMinedXRPRippleBlock401Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
