"""
    CryptoAPIs

    Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.get_omni_transaction_details_by_transaction_id_txid_ri_senders import GetOmniTransactionDetailsByTransactionIDTxidRISenders
from cryptoapis.model.list_omni_transactions_by_address_ri_recipients import ListOmniTransactionsByAddressRIRecipients
from cryptoapis.model.list_unconfirmed_omni_transactions_by_address_ri_fee import ListUnconfirmedOmniTransactionsByAddressRIFee
globals()['GetOmniTransactionDetailsByTransactionIDTxidRISenders'] = GetOmniTransactionDetailsByTransactionIDTxidRISenders
globals()['ListOmniTransactionsByAddressRIRecipients'] = ListOmniTransactionsByAddressRIRecipients
globals()['ListUnconfirmedOmniTransactionsByAddressRIFee'] = ListUnconfirmedOmniTransactionsByAddressRIFee
from cryptoapis.model.get_omni_transaction_details_by_transaction_id_txid_ri import GetOmniTransactionDetailsByTransactionIDTxidRI


class TestGetOmniTransactionDetailsByTransactionIDTxidRI(unittest.TestCase):
    """GetOmniTransactionDetailsByTransactionIDTxidRI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOmniTransactionDetailsByTransactionIDTxidRI(self):
        """Test GetOmniTransactionDetailsByTransactionIDTxidRI"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetOmniTransactionDetailsByTransactionIDTxidRI()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
