"""
    CryptoAPIs

    Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.list_wallet_transactions_e401 import ListWalletTransactionsE401
globals()['ListWalletTransactionsE401'] = ListWalletTransactionsE401
from cryptoapis.model.inline_response40145 import InlineResponse40145


class TestInlineResponse40145(unittest.TestCase):
    """InlineResponse40145 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse40145(self):
        """Test InlineResponse40145"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse40145()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
