"""
    CryptoAPIs

    Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.get_raw_transaction_data_e401 import GetRawTransactionDataE401
globals()['GetRawTransactionDataE401'] = GetRawTransactionDataE401
from cryptoapis.model.inline_response40165 import InlineResponse40165


class TestInlineResponse40165(unittest.TestCase):
    """InlineResponse40165 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse40165(self):
        """Test InlineResponse40165"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse40165()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
