"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.already_exists import AlreadyExists
from cryptoapis.model.banned_ip_address_details_inner import BannedIpAddressDetailsInner
from cryptoapis.model.invalid_data import InvalidData
globals()['AlreadyExists'] = AlreadyExists
globals()['BannedIpAddressDetailsInner'] = BannedIpAddressDetailsInner
globals()['InvalidData'] = InvalidData
from cryptoapis.model.create_automatic_coins_forwarding_e409 import CreateAutomaticCoinsForwardingE409


class TestCreateAutomaticCoinsForwardingE409(unittest.TestCase):
    """CreateAutomaticCoinsForwardingE409 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateAutomaticCoinsForwardingE409(self):
        """Test CreateAutomaticCoinsForwardingE409"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateAutomaticCoinsForwardingE409()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
