"""
    CryptoAPIs

    Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.list_unconfirmed_omni_transactions_by_property_ide400 import ListUnconfirmedOmniTransactionsByPropertyIDE400
globals()['ListUnconfirmedOmniTransactionsByPropertyIDE400'] = ListUnconfirmedOmniTransactionsByPropertyIDE400
from cryptoapis.model.inline_response40028 import InlineResponse40028


class TestInlineResponse40028(unittest.TestCase):
    """InlineResponse40028 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse40028(self):
        """Test InlineResponse40028"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse40028()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
