# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cryptoapis
from cryptoapis.models.prepare_a_transaction_from_an_address_in_hd_wallet_x_pub_y_pub_z_pub_ribst_raw_data import PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSTRawData  # noqa: E501
from cryptoapis.rest import ApiException

class TestPrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSTRawData(unittest.TestCase):
    """PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSTRawData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSTRawData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSTRawData`
        """
        model = cryptoapis.models.prepare_a_transaction_from_an_address_in_hd_wallet_x_pub_y_pub_z_pub_ribst_raw_data.PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSTRawData()  # noqa: E501
        if include_optional :
            return PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSTRawData(
                contract = cryptoapis.models.prepare_a_transaction_from_an_address_in_hd_wallet_x_pub_y_pub_z_pub_ribst_raw_data_contract.PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBST_rawData_contract(
                    parameter = cryptoapis.models.prepare_a_transaction_from_an_address_in_hd_wallet_x_pub_y_pub_z_pub_ribst_raw_data_contract_parameter.PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBST_rawData_contract_parameter(
                        amount = '3', ), )
            )
        else :
            return PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSTRawData(
                contract = cryptoapis.models.prepare_a_transaction_from_an_address_in_hd_wallet_x_pub_y_pub_z_pub_ribst_raw_data_contract.PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBST_rawData_contract(
                    parameter = cryptoapis.models.prepare_a_transaction_from_an_address_in_hd_wallet_x_pub_y_pub_z_pub_ribst_raw_data_contract_parameter.PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBST_rawData_contract_parameter(
                        amount = '3', ), ),
        )
        """

    def testPrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSTRawData(self):
        """Test PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRIBSTRawData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
