"""
    CryptoAPIs

    Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.get_address_details_ri import GetAddressDetailsRI
globals()['GetAddressDetailsRI'] = GetAddressDetailsRI
from cryptoapis.model.get_address_details_r_data import GetAddressDetailsRData


class TestGetAddressDetailsRData(unittest.TestCase):
    """GetAddressDetailsRData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAddressDetailsRData(self):
        """Test GetAddressDetailsRData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAddressDetailsRData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
