"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.banned_ip_address_details_inner import BannedIpAddressDetailsInner
from cryptoapis.model.invalid_pagination import InvalidPagination
from cryptoapis.model.limit_greater_than_allowed import LimitGreaterThanAllowed
from cryptoapis.model.uri_not_found import UriNotFound
globals()['BannedIpAddressDetailsInner'] = BannedIpAddressDetailsInner
globals()['InvalidPagination'] = InvalidPagination
globals()['LimitGreaterThanAllowed'] = LimitGreaterThanAllowed
globals()['UriNotFound'] = UriNotFound
from cryptoapis.model.prepare_autxo_based_transaction_from_hd_wallet_x_pub_y_pub_z_pub_e400 import PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubE400


class TestPrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubE400(unittest.TestCase):
    """PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubE400 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubE400(self):
        """Test PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubE400"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubE400()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
