# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cryptoapis
from cryptoapis.models.delete_blockchain_event_subscription_r import DeleteBlockchainEventSubscriptionR  # noqa: E501
from cryptoapis.rest import ApiException

class TestDeleteBlockchainEventSubscriptionR(unittest.TestCase):
    """DeleteBlockchainEventSubscriptionR unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DeleteBlockchainEventSubscriptionR
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteBlockchainEventSubscriptionR`
        """
        model = cryptoapis.models.delete_blockchain_event_subscription_r.DeleteBlockchainEventSubscriptionR()  # noqa: E501
        if include_optional :
            return DeleteBlockchainEventSubscriptionR(
                api_version = '2021-03-20', 
                request_id = '601c1710034ed6d407996b30', 
                context = 'yourExampleString', 
                data = cryptoapis.models.delete_blockchain_event_subscription_r_data.DeleteBlockchainEventSubscriptionR_data(
                    item = cryptoapis.models.delete_blockchain_event_subscription_ri.DeleteBlockchainEventSubscriptionRI(
                        callback_secret_key = 'yourSecretKey', 
                        callback_url = 'https://example.com', 
                        created_timestamp = 1611238648, 
                        event_type = 'ADDRESS_COINS_TRANSACTION_UNCONFIRMED', 
                        reference_id = '6de9a6ae-1463-458c-81a5-16d68d108012', ), )
            )
        else :
            return DeleteBlockchainEventSubscriptionR(
                api_version = '2021-03-20',
                request_id = '601c1710034ed6d407996b30',
                data = cryptoapis.models.delete_blockchain_event_subscription_r_data.DeleteBlockchainEventSubscriptionR_data(
                    item = cryptoapis.models.delete_blockchain_event_subscription_ri.DeleteBlockchainEventSubscriptionRI(
                        callback_secret_key = 'yourSecretKey', 
                        callback_url = 'https://example.com', 
                        created_timestamp = 1611238648, 
                        event_type = 'ADDRESS_COINS_TRANSACTION_UNCONFIRMED', 
                        reference_id = '6de9a6ae-1463-458c-81a5-16d68d108012', ), ),
        )
        """

    def testDeleteBlockchainEventSubscriptionR(self):
        """Test DeleteBlockchainEventSubscriptionR"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
