# coding: utf-8

"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cryptoapis
from cryptoapis.models.list_wallet_transactions_ri_internal_transactions_inner import ListWalletTransactionsRIInternalTransactionsInner  # noqa: E501
from cryptoapis.rest import ApiException

class TestListWalletTransactionsRIInternalTransactionsInner(unittest.TestCase):
    """ListWalletTransactionsRIInternalTransactionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListWalletTransactionsRIInternalTransactionsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWalletTransactionsRIInternalTransactionsInner`
        """
        model = cryptoapis.models.list_wallet_transactions_ri_internal_transactions_inner.ListWalletTransactionsRIInternalTransactionsInner()  # noqa: E501
        if include_optional :
            return ListWalletTransactionsRIInternalTransactionsInner(
                amount = '0.001', 
                converted_amount = '4.30365936483792', 
                exchange_rate_unit = 'USD', 
                operation_id = 'call_0', 
                recipient = '0x07344b7649c5ff096b0317957d9a208931d04d5e', 
                sender = '0x4b8ec9e58a8b08f3803f84fb52d0a50e84444592', 
                symbol = 'ETH'
            )
        else :
            return ListWalletTransactionsRIInternalTransactionsInner(
                amount = '0.001',
                converted_amount = '4.30365936483792',
                exchange_rate_unit = 'USD',
                operation_id = 'call_0',
                recipient = '0x07344b7649c5ff096b0317957d9a208931d04d5e',
                sender = '0x4b8ec9e58a8b08f3803f84fb52d0a50e84444592',
                symbol = 'ETH',
        )
        """

    def testListWalletTransactionsRIInternalTransactionsInner(self):
        """Test ListWalletTransactionsRIInternalTransactionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
