"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.list_internal_transaction_details_by_transaction_hash_e400 import ListInternalTransactionDetailsByTransactionHashE400
globals()['ListInternalTransactionDetailsByTransactionHashE400'] = ListInternalTransactionDetailsByTransactionHashE400
from cryptoapis.model.list_internal_transaction_details_by_transaction_hash400_response import ListInternalTransactionDetailsByTransactionHash400Response


class TestListInternalTransactionDetailsByTransactionHash400Response(unittest.TestCase):
    """ListInternalTransactionDetailsByTransactionHash400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListInternalTransactionDetailsByTransactionHash400Response(self):
        """Test ListInternalTransactionDetailsByTransactionHash400Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListInternalTransactionDetailsByTransactionHash400Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
