"""
    CryptoAPIs

    Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.banned_ip_address import BannedIpAddress
from cryptoapis.model.banned_ip_address_details import BannedIpAddressDetails
from cryptoapis.model.blockchain_events_callbacks_limit_reached import BlockchainEventsCallbacksLimitReached
from cryptoapis.model.endpoint_not_allowed_for_api_key import EndpointNotAllowedForApiKey
from cryptoapis.model.endpoint_not_allowed_for_plan import EndpointNotAllowedForPlan
from cryptoapis.model.feature_mainnets_not_allowed_for_plan import FeatureMainnetsNotAllowedForPlan
globals()['BannedIpAddress'] = BannedIpAddress
globals()['BannedIpAddressDetails'] = BannedIpAddressDetails
globals()['BlockchainEventsCallbacksLimitReached'] = BlockchainEventsCallbacksLimitReached
globals()['EndpointNotAllowedForApiKey'] = EndpointNotAllowedForApiKey
globals()['EndpointNotAllowedForPlan'] = EndpointNotAllowedForPlan
globals()['FeatureMainnetsNotAllowedForPlan'] = FeatureMainnetsNotAllowedForPlan
from cryptoapis.model.new_confirmed_coins_transactions_and_each_confirmation_e403 import NewConfirmedCoinsTransactionsAndEachConfirmationE403


class TestNewConfirmedCoinsTransactionsAndEachConfirmationE403(unittest.TestCase):
    """NewConfirmedCoinsTransactionsAndEachConfirmationE403 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewConfirmedCoinsTransactionsAndEachConfirmationE403(self):
        """Test NewConfirmedCoinsTransactionsAndEachConfirmationE403"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NewConfirmedCoinsTransactionsAndEachConfirmationE403()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
