"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.get_transaction_details_by_transaction_idribsb_vout_inner_script_pub_key import GetTransactionDetailsByTransactionIDRIBSBVoutInnerScriptPubKey
globals()['GetTransactionDetailsByTransactionIDRIBSBVoutInnerScriptPubKey'] = GetTransactionDetailsByTransactionIDRIBSBVoutInnerScriptPubKey
from cryptoapis.model.get_transaction_details_by_transaction_idribsb_vout_inner import GetTransactionDetailsByTransactionIDRIBSBVoutInner


class TestGetTransactionDetailsByTransactionIDRIBSBVoutInner(unittest.TestCase):
    """GetTransactionDetailsByTransactionIDRIBSBVoutInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTransactionDetailsByTransactionIDRIBSBVoutInner(self):
        """Test GetTransactionDetailsByTransactionIDRIBSBVoutInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTransactionDetailsByTransactionIDRIBSBVoutInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
