"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.list_deposit_addresses_r_data import ListDepositAddressesRData
globals()['ListDepositAddressesRData'] = ListDepositAddressesRData
from cryptoapis.model.list_deposit_addresses_r import ListDepositAddressesR


class TestListDepositAddressesR(unittest.TestCase):
    """ListDepositAddressesR unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListDepositAddressesR(self):
        """Test ListDepositAddressesR"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListDepositAddressesR()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
