"""
    CryptoAPIs

    Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.new_unconfirmed_tokens_transactions_e401 import NewUnconfirmedTokensTransactionsE401
globals()['NewUnconfirmedTokensTransactionsE401'] = NewUnconfirmedTokensTransactionsE401
from cryptoapis.model.inline_response40159 import InlineResponse40159


class TestInlineResponse40159(unittest.TestCase):
    """InlineResponse40159 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse40159(self):
        """Test InlineResponse40159"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse40159()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
