"""
    CryptoAPIs

    Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.  # noqa: E501

    The version of the OpenAPI document: 2021-03-20
    Contact: developers@cryptoapis.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cryptoapis
from cryptoapis.model.list_xrp_ripple_transactions_by_address_and_time_range_e400 import ListXRPRippleTransactionsByAddressAndTimeRangeE400
globals()['ListXRPRippleTransactionsByAddressAndTimeRangeE400'] = ListXRPRippleTransactionsByAddressAndTimeRangeE400
from cryptoapis.model.list_xrp_ripple_transactions_by_address_and_time_range400_response import ListXRPRippleTransactionsByAddressAndTimeRange400Response


class TestListXRPRippleTransactionsByAddressAndTimeRange400Response(unittest.TestCase):
    """ListXRPRippleTransactionsByAddressAndTimeRange400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListXRPRippleTransactionsByAddressAndTimeRange400Response(self):
        """Test ListXRPRippleTransactionsByAddressAndTimeRange400Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListXRPRippleTransactionsByAddressAndTimeRange400Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
